/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Conexao;
import entidade.Lugar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author YuGiOh
 */
public class FmrApresenta extends javax.swing.JFrame {

    /**
     * Creates new form FmrApresenta
     */
    public FmrApresenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelImg = new javax.swing.JPanel();
        lblImagem = new javax.swing.JLabel();
        panelBanner = new javax.swing.JPanel();
        lblBanner = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblSite = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblFiltroCategoria = new javax.swing.JLabel();
        lblFiltroZona = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelImg.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout painelImgLayout = new javax.swing.GroupLayout(painelImg);
        painelImg.setLayout(painelImgLayout);
        painelImgLayout.setHorizontalGroup(
            painelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelImgLayout.setVerticalGroup(
            painelImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        painelPrincipal.add(painelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, 310));

        panelBanner.setBackground(new java.awt.Color(102, 102, 255));

        lblBanner.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblBanner.setForeground(new java.awt.Color(255, 255, 255));
        lblBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanner.setText("CONTROLE DE LUGARES");

        javax.swing.GroupLayout panelBannerLayout = new javax.swing.GroupLayout(panelBanner);
        panelBanner.setLayout(panelBannerLayout);
        panelBannerLayout.setHorizontalGroup(
            panelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBanner, javax.swing.GroupLayout.DEFAULT_SIZE, 1238, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBannerLayout.setVerticalGroup(
            panelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBannerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblBanner)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        painelPrincipal.add(panelBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 100));

        lblEndereco.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblEndereco.setText("jLabel1");
        painelPrincipal.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        lblDescricao.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblDescricao.setText("jLabel2");
        painelPrincipal.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        lblSite.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblSite.setText("jLabel3");
        painelPrincipal.add(lblSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        lblNome.setFont(new java.awt.Font("Verdana", 1, 26)); // NOI18N
        lblNome.setText("jLabel4");
        painelPrincipal.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblFiltroCategoria.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblFiltroCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFiltroCategoria.setText("jLabel1");

        lblFiltroZona.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblFiltroZona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFiltroZona.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFiltroCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(lblFiltroZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblFiltroCategoria)
                .addGap(28, 28, 28)
                .addComponent(lblFiltroZona)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        painelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, 220));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Filtro");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        painelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 30));

        getContentPane().add(painelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -4, 1170, 640));

        setSize(new java.awt.Dimension(1171, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrApresenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrApresenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrApresenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrApresenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrApresenta().setVisible(true);
            }
        });
    }
    
    
    public void recebeLugareZonaSelectionado(String zona, String categoria){
        if ((zona != null) && (categoria != null) ) {
          
            Conexao con = new Conexao();
            Lugar lugar = new Lugar();
            Boolean retorno = con.conectarDB();
            
            lugar = con.buscaLugar(zona, categoria);
            if (retorno) { 
                if (lugar != null){                    
                    lblBanner.setText       ("Conheça: " + lugar.getNome());
                    lblNome.setText         ("Nome: " + lugar.getNome());
                    lblEndereco.setText     ("Endereço: " + lugar.getEndereco());
                    lblSite.setText         ("Site: " + lugar.getSite());
                    lblDescricao.setText    ("Descrição: " + lugar.getDescricao());
                    
                    if (lugar.getImg() != null) {
                        ImageIcon icone = new ImageIcon(lugar.getImg());
                        icone.setImage(
                                icone.getImage().getScaledInstance(painelImg.getWidth() - 5,
                                painelImg.getHeight() - 10, 100)
                        );
                        
                        lblImagem.setIcon(icone);
                    } else {
                        lblImagem.setText   ("Não Há Imagem Disponivel!");
                    }
                    // Labels Filtro
                    lblFiltroCategoria.setText  (lugar.getCategoria());
                    lblFiltroZona.setText       (lugar.getZona());
                } else {
                    JOptionPane.showMessageDialog(null, "Lugar não encontrado !");       
                }
            } else {
                 JOptionPane.showMessageDialog(null, "Erro na conexão com o Banco !");
            }
        }else {
            JOptionPane.showMessageDialog(null, "Erro em chamar o forme para alteração");
        }
        /*lblNome.setText(zona);
        lblEndereco.setText(categoria);
*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFiltroCategoria;
    private javax.swing.JLabel lblFiltroZona;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSite;
    private javax.swing.JPanel painelImg;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel panelBanner;
    // End of variables declaration//GEN-END:variables
}
