/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author YuGiOh
 */
public class FrmSplash extends javax.swing.JFrame {

    /**
     * Creates new form FrmSplash
     */
    public FrmSplash() {
        initComponents();
        
        new Thread() {
            public void run () {
                for (int i = 0; i < 101; i++) {
                    try {
                        sleep(100);
                        lblProgresso.setText(String.valueOf(i) + "%");
                        
                        if (i <= 40) {
                            lblSplash.setText("Carregando Base de Dados...");
                        } 
                        else if (i <= 70) {
                            lblSplash.setText("Carregando Catalogo dos Melhores Lugares...");
                        }
                        else if (i == 100){
                            lblSplash.setText("Entrando No Sistema...");
                            FrmPrincipal fmrP = new FrmPrincipal();
                            fmrP.setVisible(true);
                            dispose();
                        }  
                    }
                    catch (Exception e) {
                    }
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblProgresso = new javax.swing.JLabel();
        lblSplash = new javax.swing.JLabel();
        lblVersao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Loading.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 140, 40));

        lblProgresso.setFont(new java.awt.Font("Comic Sans MS", 1, 25)); // NOI18N
        lblProgresso.setForeground(new java.awt.Color(0, 0, 0));
        lblProgresso.setText("0%");
        jPanel1.add(lblProgresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 70, 40));

        lblSplash.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblSplash.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSplash.setText("asasa");
        jPanel1.add(lblSplash, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 320, -1));

        lblVersao.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblVersao.setForeground(new java.awt.Color(0, 0, 0));
        lblVersao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVersao.setText("Versão: 0.8");
        jPanel1.add(lblVersao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banner-splash.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        setSize(new java.awt.Dimension(619, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSplash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblProgresso;
    private javax.swing.JLabel lblSplash;
    private javax.swing.JLabel lblVersao;
    // End of variables declaration//GEN-END:variables
}
